// Code generated by protoc-gen-go.
// source: task.proto
// DO NOT EDIT!

/*
Package tasks is a generated protocol buffer package.

It is generated from these files:
	task.proto

It has these top-level messages:
	Task
	Response
	Cancel
*/
package tasks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task_PriorityType int32

const (
	Task_LOW  Task_PriorityType = 0
	Task_HIGH Task_PriorityType = 1
)

var Task_PriorityType_name = map[int32]string{
	0: "LOW",
	1: "HIGH",
}
var Task_PriorityType_value = map[string]int32{
	"LOW":  0,
	"HIGH": 1,
}

func (x Task_PriorityType) String() string {
	return proto.EnumName(Task_PriorityType_name, int32(x))
}
func (Task_PriorityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// [START messages]
type Task struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	NewName  string `protobuf:"bytes,2,opt,name=new_name,json=newName" json:"new_name,omitempty"`
	Format   string `protobuf:"bytes,3,opt,name=format" json:"format,omitempty"`
	Priority int32  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	FileId   string `protobuf:"bytes,5,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Task) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *Task) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Task) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Task) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type Response struct {
	FileLocation string `protobuf:"bytes,1,opt,name=file_location,json=fileLocation" json:"file_location,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

type Cancel struct {
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *Cancel) Reset()                    { *m = Cancel{} }
func (m *Cancel) String() string            { return proto.CompactTextString(m) }
func (*Cancel) ProtoMessage()               {}
func (*Cancel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cancel) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "tasks.Task")
	proto.RegisterType((*Response)(nil), "tasks.Response")
	proto.RegisterType((*Cancel)(nil), "tasks.Cancel")
	proto.RegisterEnum("tasks.Task_PriorityType", Task_PriorityType_name, Task_PriorityType_value)
}

func init() { proto.RegisterFile("task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x5f, 0x6b, 0xc2, 0x30,
	0x14, 0xc5, 0x17, 0xed, 0xbf, 0xdd, 0x39, 0x90, 0x3c, 0xb8, 0xce, 0x27, 0xed, 0x5e, 0x7c, 0xea,
	0x06, 0x7b, 0xda, 0x6b, 0x07, 0x53, 0x41, 0x36, 0x29, 0xc2, 0x1e, 0x25, 0xd6, 0xdb, 0x2d, 0xd8,
	0x26, 0xa5, 0xc9, 0x10, 0xbf, 0xd2, 0x60, 0xdf, 0x71, 0x24, 0x86, 0xe2, 0x5b, 0xce, 0xfd, 0xdd,
	0x9c, 0x73, 0x39, 0x00, 0x9a, 0xa9, 0x43, 0xda, 0xb4, 0x52, 0x4b, 0xea, 0x9b, 0xb7, 0x4a, 0xfe,
	0x08, 0x78, 0x1b, 0xa6, 0x0e, 0x74, 0x0c, 0x51, 0xc9, 0x2b, 0x14, 0xac, 0xc6, 0x98, 0x4c, 0xc8,
	0xec, 0x3a, 0xef, 0x34, 0xbd, 0x87, 0x48, 0xe0, 0x71, 0x6b, 0x59, 0xcf, 0xb2, 0x50, 0xe0, 0xf1,
	0xdd, 0xa0, 0x11, 0x04, 0xa5, 0x6c, 0x6b, 0xa6, 0xe3, 0xbe, 0x05, 0x4e, 0x19, 0xbb, 0xa6, 0xe5,
	0xb2, 0xe5, 0xfa, 0x14, 0x7b, 0x13, 0x32, 0xf3, 0xf3, 0x4e, 0xd3, 0x3b, 0x08, 0x8d, 0xf5, 0x96,
	0xef, 0x63, 0xdf, 0x7d, 0xe2, 0x15, 0x2e, 0xf7, 0xc9, 0x14, 0x06, 0x6b, 0xb7, 0xb4, 0x39, 0x35,
	0x48, 0x43, 0xe8, 0xaf, 0x3e, 0x3e, 0x87, 0x57, 0x34, 0x02, 0x6f, 0xb1, 0x9c, 0x2f, 0x86, 0x24,
	0x79, 0x84, 0x28, 0x47, 0xd5, 0x48, 0xa1, 0x90, 0x3e, 0xc0, 0xad, 0xf5, 0xa9, 0x64, 0xc1, 0x34,
	0x97, 0xc2, 0xdd, 0x3d, 0x30, 0xc3, 0x95, 0x9b, 0x25, 0x53, 0x08, 0x5e, 0x99, 0x28, 0xb0, 0xba,
	0x8c, 0x25, 0x97, 0xb1, 0x59, 0x06, 0xe3, 0x42, 0xd6, 0xe9, 0x17, 0xd7, 0xdf, 0x3f, 0xbb, 0xb4,
	0xc4, 0xb6, 0x60, 0x75, 0xf3, 0xf4, 0x92, 0xda, 0x86, 0xb2, 0x1b, 0x53, 0x8f, 0x5a, 0x9b, 0xd2,
	0xd4, 0x6f, 0x6f, 0xf4, 0xd6, 0xe1, 0xf9, 0x79, 0xdf, 0xe2, 0x5d, 0x60, 0x5b, 0x7d, 0xfe, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xf9, 0x82, 0x7a, 0x63, 0x01, 0x00, 0x00,
}
