# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='tasks',
  syntax='proto3',
  serialized_pb=_b('\n\ntask.proto\x12\x05tasks\"\x80\x01\n\x04Task\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x0f\n\x07\x66ile_id\x18\x05 \x01(\t\"!\n\x0cPriorityType\x12\x07\n\x03LOW\x10\x00\x12\x08\n\x04HIGH\x10\x01\"!\n\x08Response\x12\x15\n\rfile_location\x18\x01 \x01(\t\"\x19\n\x06\x43\x61ncel\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\tBB\n\x1a\x63om.github.fercamp09.tasksB\x0bTasksProtos\xaa\x02\x16\x46\x65rcamp09.Github.Tasksb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TASK_PRIORITYTYPE = _descriptor.EnumDescriptor(
  name='PriorityType',
  full_name='tasks.Task.PriorityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=117,
  serialized_end=150,
)
_sym_db.RegisterEnumDescriptor(_TASK_PRIORITYTYPE)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='tasks.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='tasks.Task.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_name', full_name='tasks.Task.new_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='tasks.Task.format', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='tasks.Task.priority', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_id', full_name='tasks.Task.file_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_PRIORITYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=150,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='tasks.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_location', full_name='tasks.Response.file_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=185,
)


_CANCEL = _descriptor.Descriptor(
  name='Cancel',
  full_name='tasks.Cancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='tasks.Cancel.file_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=212,
)

_TASK_PRIORITYTYPE.containing_type = _TASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Cancel'] = _CANCEL

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Task)
  ))
_sym_db.RegisterMessage(Task)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Response)
  ))
_sym_db.RegisterMessage(Response)

Cancel = _reflection.GeneratedProtocolMessageType('Cancel', (_message.Message,), dict(
  DESCRIPTOR = _CANCEL,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Cancel)
  ))
_sym_db.RegisterMessage(Cancel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.github.fercamp09.tasksB\013TasksProtos\252\002\026Fercamp09.Github.Tasks'))
# @@protoc_insertion_point(module_scope)
